# apiVersion: APIGROUP/KIND
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Changes port to 110"
  name: deployment-test
  labels:
    app: front
#ReplicaSet
spec:
 # Set the number of revision for the replicasets objects
 # revisionHistoryLimit: 1
  replicas: 5
  selector:
    matchLabels:
      app: front
  # Pod
  template:
    metadata:
      labels: 
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 110